### PR TITLE
[WIP] Expand tags

### PR DESCRIPTION
**Pull request by AnneTee**
Everything works except the transitions, which are proving to be extremely tricky

### CODE REVIEW

**Comment by egardner** [comment]
I'll review this in depth tomorrow, but a couple of quick thoughts on first glance:
1. Looks like the toggle switch component is mutating its props directly; we may need to do something where initial state is passed as a prop and local (mutable) state is maintained separately in `data`. Or just emit an event upwards and don't change the state locally at all, accept a new prop instead.
2. I think part of why the transitions are so tricky here is that markup for the `<Suggestion>` and `<SuggestionGroup>` is pretty complex, because of the reliance on `<slot>` and `<template>` tags. I know we were treating the simple version of the Suggestion component as potentially re-usable hence those design decisions; I am not sure that the this still applies to the version that can toggle between states. If we treat this expandable Suggestion component as something that is MV-specific, then we can rewrite `<Suggestion>` to simply use v-if and keep both versions of the markup in one place. This will probably make it a lot easier to get transitions working.

**Comment by AnneTee** [comment]
1. I'll take a look and update this!
2. A [list move transition](https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions) is exactly what we need here – Vue uses the FLIP technique to smoothly transform transition group items that have moved. We're not actually moving suggestions in the DOM when we add the details, but we could in theory spoof this by adding an invisible element or something. I say in theory because I've been trying to get this working (by shuffling the suggestions, similar to what's done in the docs) but I can't get the move transition to trigger yet.

**Comment by AnneTee** [comment]
Update: I've gotten the tags to move smoothly to their new location (turns out you don't actually have to update the DOM order; I just wasn't seeing a transition before because I had other transitions applied that were overriding the ones I wanted). But, there are some bugs, and some other transitions that need to be added. I'll keep working on this but it will likely take some time!

**Comment by AnneTee** [comment]
Closing in favor of https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MachineVision/+/601400

**Pull request closed without merging**
