### PR TITLE
Call existing OOUI onboarding dialog from Vue

### PR DESCRIPTION
**Pull request by egardner**
Re-implementing the global process dialog and window manager functionality in
OOUI is currently beyond the scope of this project.

For now, it seems like the best approach will be to treat dialogs as a system
boundary; Vue components can launch dialogs by firing methods as normal, but
they will have no knowledge of or control over what happens in those dialogs
(unless an event is emitted that the component is listening for).

This change mostly just copies over some pre-existing widgets without changing
them (file import paths have been altered slightly but that's it).

Some modifications to linting and testing are also required to allow the two
frameworks to co-exist for now.

Change-Id: I6cfb23facc43c4a107bf849434faac8cf3cb5e27

### CODE REVIEW

**Review by AnneTee — APPROVED** [review]
@egardner I pushed a commit that will only run the showOnboardingDialog method if we're on the user tab (and fixes an outstanding code style issue). This makes sense for now and works as expected. Maybe once we have everything else completed we can return to this, especially given Moriel's comment that we could consider a different paradigm than WindowManager + Dialog.

Please check over my commit then feel free to merge!

**Comment by egardner** [comment]
> @egardner I pushed a commit that will only run the showOnboardingDialog method if we're on the user tab (and fixes an outstanding code style issue). This makes sense for now and works as expected. Maybe once we have everything else completed we can return to this, especially given Moriel's comment that we could consider a different paradigm than WindowManager + Dialog.

In this case, first-time visitors who land on the page without the `#user` hash in the URL will not see the dialog at all (even if they switch tabs after landing). Is this acceptable behavior?

**Comment by AnneTee** [comment]
@egardner good call – we need to show it the first time a user visits the user tab, no matter how they get there.

**Comment by AnneTee** [comment]
We can just call the onboarding dialog method from the `currentTab` watcher since `updateCurrentTab` is called on mount. This should do it!

**Pull request merged**
